core:
  ssh_authorized_keys:
    - <MY PUBLIC SSH KEY>

adguardhome:
  version_tag: latest
  macvlan:
    interface : eth0
    subnet: 192.168.0.0/24
    gateway: 192.168.0.1
  ip: 192.168.0.10

ext4_drives:
  - uuid: <BLOC-DEVICE-UUID>
    mount_point: /var/hdd
    placeholder_folders:
      - Movies
      - Shows
      - Music
      - Photos

caddy:
  version_tag: 2.10
  https_redirections:
    - route: jellyfin.mydomain.com
      internal_port: 3002
    - route: overleaf.mydomain.com
      internal_port: 3004
    - route: forgejo.mydomain.com
      internal_port: 3005
    - route: immich.mydomain.com
      internal_port: 3006
    - route: joplin.mydomain.com
      internal_port: 3007

jellyfin:
  version_tag: 10
  http_port: 3002
  media_volumes:
    - /var/hdd/Movies:/media/Movies:ro,Z
    - /var/hdd/Shows:/media/Shows:ro,Z
    - /var/hdd/Music:/media/Music:ro,Z
  self_url: jellyfin.mydomain.com

overleaf:
  mongo_version_tag: 8.0
  redis_version_tag: 7.4
  sharelatex_image: docker.io/rigon/sharelatex-full:6.0.0
  http_port: 3004
  app_name: My Overleaf
  self_url: overleaf.mydomain.com
  admin_email: <MY EMAIL>

forgejo:
  version_tag: 13
  http_port: 3005
  ssh_port: 2222

immich:
  postgres_version_tag: 14-vectorchord0.4.3-pgvectors0.2.0
  valkey_version_tag: 8
  immich_version_tag: v2
  http_port: 3006
  host_drive_type: SSD
  photos_volume: /var/hdd/Photos

joplin:
  postgres_version_tag: 16
  joplin_version_tag: 3.5
  http_port: 3007
  self_url: joplin.mydomain.com